trigger:
- main

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'
  uipathProjectName: 'UiPath Orchestration'
  uipathPackageName: '$(uipathProjectName).$(Build.BuildId).nupkg'
  uipathProjectPath: '$(Build.SourcesDirectory)/src/UiPath Orchestration'

steps:
- task: UiPathPack@2
  displayName: 'Pack UiPath Project'
  inputs:
    projectPath: '$(uipathProjectPath)'
    outputType: 'NuGet'
    outputName: '$(uipathPackageName)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: UiPathPackage'
  inputs:
    pathToPublish: '$(Build.SourcesDirectory)/$(uipathPackageName)'
    artifactName: 'UiPathPackage'

