trigger:
- main

pool:
  name: 'Default'

- task: UiPathInstallPlatform@4
  inputs:
    cliVersion: 'WIN_23.10.8894.39673'

- task: UiPathAssets@4
  inputs:
    orchestratorConnection: 'UiPath_Service_Connection_007'
    folderName: 'New'
    assetActionType: 'Deploy'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'UiPath_Service_Connection_007'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

